[tool.bandit]
exclude_dirs = ["/tests","dos_db_handler"]
skips = ["B101"]

[tool.vulture]
make_whitelist = true
paths=["."]
exclude = [
  "change_event_dlq_handler/tests",
  "common/tests",
  "comparison_reporting/tests",
  "dos_db_handler/tests",
  "dos_db_update_dlq_handler/tests",
  "event_replay/tests",
  "orchestrator/tests",
  "send_email/tests",
  "service_matcher/tests",
  "service_sync/tests",
  "slack_messenger/tests",
  ]
sort_by_size = true
ignore_names = [
  "email_body",
  "email_subject",
  "encoding",
  "field_names",
  "is_health_check",
  "lambda_handler",
  "metadata",
  "recipient_email_address",
  "recipient_id",
  ]
