[tool.bandit]
exclude_dirs = ["/tests","dos_db_handler"]
skips = ["B101"]

[tool.vulture]
make_whitelist = true
paths=["."]
exclude = [
  "/tests",
  ]
sort_by_size = true
min_confidence = 100
ignore_names = [
  "email_body",
  "email_subject",
  "encoding",
  "field_names",
  "is_health_check",
  "lambda_handler",
  "metadata",
  "recipient_email_address",
  "recipient_id",
  ]
