[tool.bandit]
exclude_dirs = ["/tests","dos_db_handler"]
skips = ["B101"]

[tool.vulture]
make_whitelist = true
paths=["."]
exclude = [
  "change_event_dlq_handler/tests",
  "common/tests",
  "comparison_reporting/tests",
  "dos_db_handler/tests",
  "dos_db_update_dlq_handler/tests",
  "event_replay/tests",
  "orchestrator/tests",
  "service_matcher/tests",
  "service_sync/tests",
  "slack_messenger/tests"
  ]
sort_by_size = true
ignore_names = [
  "lambda_handler",
  "*db_connection",
  "field_names",
  "recipient_id",
  "encoding",
  "metadata",
  "put_circuit_is_open"
  ]
