version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "application"
    schedule:
      interval: "daily"
    target-branch: "develop"
  # Maintain dependencies for Dockerfile
  - package-ecosystem: "docker"
    directory: "build/docker"
    schedule:
      interval: "daily"
    target-branch: "develop"
  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "infrastructure/modules/s3"
    schedule:
      interval: "daily"
    target-branch: "develop"
  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "infrastructure/stacks"
    schedule:
      interval: "daily"
    target-branch: "develop"
