[tool.ruff]
select = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "I",
  "N",
  "Q",
  "S",
  "T",
  "W",
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "DJ",
  "DTZ",
  "EM",
  "ERA",
  "EXE",
  "ICN",
  "INP",
  "ISC",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "TID",
  "TRY",
  "UP",
  "YTT",
]
ignore = [
  "D100",    # Missing docstring in public module
  "D104",    # Missing docstring in public package
  "PTH123",  # Use `pathlib.Path` instead of `os.path`
  "G004",    # Logging statement uses f-string
  "PLR0913", # Too many arguments in function call
  "DTZ007",  # Allow Datetime used as timezone in tests.
  "TID252",  # Allow Relative imports from parent modules
  "COM812",  # Ignore due to conflict with Ruff formatter
  "ISC001",  # Ignore due to conflict with Ruff formatter
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "I",
  "N",
  "Q",
  "S",
  "T",
  "W",
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "DJ",
  "DTZ",
  "EM",
  "ERA",
  "EXE",
  "FLY",
  "FBT",
  "ICN",
  "INP",
  "PERF",
  "FURB",
  "ISC",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "TCH",
  "TID",
  "TRY",
  "UP",
  "YTT",
]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Set target version to Python 3.11.
target-version = "py311"

[tool.ruff.per-file-ignores]
"application/**test_*.py" = [
  "S101",    # Allow `assert` in tests.
  "S105",    # Allow fake secrets in tests.
  "SLF001",  # Allow `_function` in tests.
  "PLR0913", # Allow many arrguments in tests.
  "ARG001",  # Unused function argument
  "D101",    # Allow Missing docstring in public class
  "D102",    # Allow Missing docstring in public method
  "D103",    # Allow missing docstring in tests.
  "S311",    # Allow Standard pseudo-random generators are not suitable for cryptographic purposes in tests.
  "PLR2004", # Allow Magic value used in comparison, consider replacing 20 with a constant variable in tests.
  "S608",    # Allow Possible SQL injection vector through string concatenation in tests.
  "DTZ001",  # The use of `datetime.datetime.now()` without `tz` argument is not allowed in tests.
  "DTZ005",  # The use of `datetime.datetime.now()` without `tz` argument is not allowed in tests.

]

"application/**conftest.py" = [
  "S311", # Allow Standard pseudo-random generators are not suitable for cryptographic purposes in tests.
]


"scripts/performance_test_results*.py" = [
  "T201", # Allow print statements in scripts.
]

[tool.ruff.pydocstyle]
convention = "google" # Use Google docstring convention.

[tool.ruff.isort]
known-local-folder = [
  "application",
  "common",
  "functions",
  "tests",
  "integration",
]
