version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - make docker-hub-signin
      - make docker-pull NAME=tester VERSION=latest
  build:
    commands:
      - echo "[Running Load Tests]"
      - make load-test-in-pipeline PROFILE=perf ENVIRONMENT=perf
