version: 0.2

phases:
  pre_build:
    commands:
      - make docker-hub-signin
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - make docker-pull NAME=tester VERSION=latest
  build:
    commands:
      - echo "[Running Stress Tests]"
      - make stress-test-in-pipeline PROFILE=perf ENVIRONMENT=perf
