# For documentation see here - https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
service: ${env:PROGRAMME}-${env:TEAM_ID}
frameworkVersion: '2'
variablesResolutionMode: 20210326
configValidationMode: error
unresolvedVariablesNotificationMode: error

provider:
  name: aws
  lambdaHashingVersion: 20201221
  architecture: x86_64
  region: ${env:AWS_REGION}
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: true
  tags:
    Environment: ${env:ENVIRONMENT}
    PROFILE: ${env:PROFILE}
    Product: ${env:PROJECT_GROUP_SHORT}
    Programme: ${env:PROGRAMME}
    Service: ${env:PROJECT_GROUP_SHORT}
  apiGateway:
    apiKeySourceType: HEADER
    apiKeys:
      - name: NHS_UK_API_KEY
        value: ${self:custom.secret.NHS_UK_API_KEY}
custom:
  secret: ${ssm:/aws/reference/secretsmanager/uec-dos-int-dev-api-key}

  # iam:
  #   role:
  #     name: dos-integration-${sls:stage}-lambda-role
  #     statements:
        # - Effect: 'Allow'
        #   Resource: 'TODO'
        #   Action: 'TODO' #This need to be restricted when used
        # - Effect: 'Deny'
        #   Resource: 'TODO'
        #   Action: 'TODO'

plugins:
  - serverless-vpc-discovery
  - serverless-localstack

# custom:
#   vpcDiscovery:
#     # Documentation - https://www.serverless.com/plugins/serverless-vpc-discovery
#     vpcName: '${env:AWS_VPC_NAME}'
#     subnets:
#       - tagKey: Name
#         tagValues:
#           - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}a'
#           - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}b'
#           - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}c'
#     securityGroups:
#       - tagKey: Name
#         tagValues:
#           - 'uec-pu-apu-2429-rds'

functions:
  event-receiver:
    image: ${env:AWS_SAME_ACCOUNT_DOCKER_REGISTRY}/event-receiver:latest
    architecture: x86_64
    tracing: Active
    name: ${env:PROJECT_ID}-${sls:stage}-event-receiver
    description: ${sls:stage} Event Receiver lambda
    memorySize: 512
    timeout: 10
    tags:
      PYTHON_VERSION: ${env:PYTHON_VERSION}
    environment:
      PROFILE: ${env:PROFILE}
      POWERTOOLS_SERVICE_NAME: ${env:TEAM_ID}
      POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
      POWERTOOLS_TRACER_CAPTURE_ERROR: true
      POWERTOOLS_TRACE_MIDDLEWARES: true
      LOG_LEVEL: ${env:LOG_LEVEL}
    events:
      - http:
        path: /dos-integration/api/v1/nhsuk-event-receiver/{type}
        request:
          parameters:
            paths:
              type: true # pharmacy /dental
        method: post
        private: true
  event-sender:
    image: ${env:AWS_SAME_ACCOUNT_DOCKER_REGISTRY}/event-sender:latest
    architecture: x86_64
    tracing: Active
    name: ${env:PROJECT_ID}-${sls:stage}-event-sender
    description: ${sls:stage} Event Sender lambda
    memorySize: 512
    timeout: 10
    tags:
      PYTHON_VERSION: ${env:PYTHON_VERSION}
    environment:
      PROFILE: ${env:PROFILE}
      POWERTOOLS_SERVICE_NAME: ${env:TEAM_ID}
      POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
      POWERTOOLS_TRACER_CAPTURE_ERROR: true
      POWERTOOLS_TRACE_MIDDLEWARES: true
      LOG_LEVEL: ${env:LOG_LEVEL}

#resources:
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
