# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECDoSINTPipelineBuildRole" --role-session-name "CodeBuildSessionNonProd")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - make docker-hub-signin
  build:
    commands:
      - make build-and-deploy PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - make integration-test PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT PARALLEL_TEST_COUNT=20 TAGS=pharmacy

reports:
  PytestIntegrationReport:
    files:
      - "testresults.json"
    base-directory: $CODEBUILD_SRC_DIR/test/integration
    discard-paths: yes
    file-format: CUCUMBERJSON
