# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  build:
    commands:
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECDoSINTPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make aws-ecr-cleanup REPOS=cr-fifo-dlq-handler,event-processor,event-replay,event-sender,fifo-dlq-handler,slack-messenger,test-db-checker-handler,orchestrator,tester,serverless,dos-db-update-dlq-handler,service-matcher,service-sync,change-event-dlq-handler,dos-db-handler
    finally:
        - |
          if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
            make slack-codebuild-notification PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT PIPELINE_NAME="Delete ECR Images" BUILD_STATUS=failure CODEBUILD_PROJECT_NAME=$CB_PROJECT_NAME CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID SLACK_MESSAGE="Delete Failed Please investigate"
          fi
