# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/cli/cli/releases/download/v2.6.0/gh_2.6.0_linux_amd64.rpm
      - yum localinstall -y gh_2.6.0_linux_amd64.rpm
  pre_build:
    commands:
      - export GH_TOKEN=$(make secret-fetch NAME=uec-dos-int-tools/deployment | jq -r '.GITHUB_TOKEN')
      - echo $GH_TOKEN
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/$PIPELINE_BUILD_ROLE" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make docker-hub-signin
  build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - export PR_NUMBER=$(echo $CODEBUILD_WEBHOOK_TRIGGER | grep -Eo '[0-9]*')
      - echo $PR_NUMBER
      - export ENVIRONMENT=$(make -s get-environment-from-pr PR_NUMBER=$PR_NUMBER)
      - echo $ENVIRONMENT
      - |
        if [[ "$ENVIRONMENT" =~ .*"ds-".* ]]; then
          export ENVIRONMENT_DEPLOYED=$(aws lambda get-function --function-name uec-dos-int-$ENVIRONMENT-service-sync)
          make undeploy PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT OPTS="-parallelism=30";
        fi
    finally:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          make slack-codebuild-notification ENVIRONMENT=$ENVIRONMENT PROFILE=$PROFILE PIPELINE_NAME="Delete Environment After Merge Codebuild Stage" BUILD_STATUS=failure CODEBUILD_PROJECT_NAME=$CB_PROJECT_NAME CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID SLACK_MESSAGE="Delete Failed Please investigate"
        else
          make slack-codebuild-notification ENVIRONMENT=$ENVIRONMENT PROFILE=$PROFILE PIPELINE_NAME="Delete Environment After Merge Codebuild Stage" BUILD_STATUS=success CODEBUILD_PROJECT_NAME=$CB_PROJECT_NAME CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID SLACK_MESSAGE="Delete Succeeded"
        fi
