# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - echo Trigger = $CODEBUILD_WEBHOOK_TRIGGER
      - export DEPLOYMENT_VERSION=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed -e "s|^tag/||" | sed -e "s|^-cicd||")
      - echo TAG = $DEPLOYMENT_VERSION
  build:
    commands:
      - cd ..
      - zip -r $DEPLOYMENT_VERSION-$CODEBUILD_START_TIME.zip dos-integration
      - aws s3 cp $DEPLOYMENT_VERSION-$CODEBUILD_START_TIME.zip s3://$CICD_ARTIFACT_BUCKET/$DEPLOYMENT_VERSION-$CODEBUILD_START_TIME.zip
