version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make docker-hub-signin
      - make docker-pull NAME=serverless VERSION=latest
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - export ENVIRONMENT=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed -e "s|^tag/||" -e "s|-destroy.*||")
      - echo $ENVIRONMENT
      - export ENVIRONMENT_DEPLOYED=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --max-items 1000 | jq --raw-output '.StackSummaries[] | select(.StackName | contains("'$ENVIRONMENT'"))')
      - echo $ENVIRONMENT_DEPLOYED
      - if [ -n "$ENVIRONMENT_DEPLOYED" ]; then
          make undeploy PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT ;
        fi
