# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - printenv
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make docker-hub-signin
      - make docker-pull NAME=serverless VERSION=latest
  build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - export ENVIRONMENT=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed -e "s|refs/heads/release/||" | sed -e "s|\.|-|g")
      - export RELEASE_BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed -e "s|refs/heads/||")
      - echo $ENVIRONMENT
      - export TEST_ENV=$(echo $ENVIRONMENT-test)
      - echo $TEST_ENV
      - export ENVIRONMENT_DEPLOYED=$(make -s is-environment-deployed ENVIRONMENT=$TEST_ENV)
      - echo $ENVIRONMENT_DEPLOYED
      - |
        if [ -n "$ENVIRONMENT_DEPLOYED" ]; then
          make terraform-clean
          make undeploy PROFILE=test ENVIRONMENT=$TEST_ENV
          unset ENVIRONMENT_DEPLOYED
        fi
      - export PERF_ENV=$(echo $ENVIRONMENT-perf)
      - echo $PERF_ENV
      - export ENVIRONMENT_DEPLOYED=$(make -s is-environment-deployed ENVIRONMENT=$PERF_ENV)
      - echo $ENVIRONMENT_DEPLOYED
      - |
        if [ -n "$ENVIRONMENT_DEPLOYED" ]; then
          make terraform-clean
          make undeploy PROFILE=perf ENVIRONMENT=$PERF_ENV
          unset ENVIRONMENT_DEPLOYED
        fi
      - unset AWS_ACCESS_KEY_ID
      - unset AWS_SECRET_ACCESS_KEY
      - unset AWS_SESSION_TOKEN
      - temp_prod_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_PROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSessionProd")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_prod_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_prod_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_prod_role | jq -r .Credentials.SessionToken)
      - export DEMO_ENV=$(echo $ENVIRONMENT-demo)
      - echo $DEMO_ENV
      - export ENVIRONMENT_DEPLOYED=$(make -s is-environment-deployed ENVIRONMENT=$DEMO_ENV)
      - echo $ENVIRONMENT_DEPLOYED
      - |
        if [ -n "$ENVIRONMENT_DEPLOYED" ]; then
            make terraform-clean
            make undeploy PROFILE=demo ENVIRONMENT=$DEMO_ENV
        fi
      - unset AWS_ACCESS_KEY_ID
      - unset AWS_SECRET_ACCESS_KEY
      - unset AWS_SESSION_TOKEN
      - make terraform-clean
      - make terraform-destroy-auto-approve PROFILE=tools ENVIRONMENT=$ENVIRONMENT STACKS=release-pipeline,perf-test-tools TF_VAR_release_pipeline_branch=$RELEASE_BRANCH TF_VAR_from_release_branch=true
