# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - wget https://github.com/cli/cli/releases/download/v2.6.0/gh_2.6.0_linux_amd64.rpm
      - yum localinstall -y gh_2.6.0_linux_amd64.rpm
      - gh version
  pre_build:
    commands:
      - make wait-for-codebuild-to-finish PROJECT_NAME=$SERVERLESS_BUILD_PROJECT_NAME
      - export GH_TOKEN=$(make secret-fetch NAME=uec-dos-int-tools/deployment | jq -r '.GITHUB_TOKEN')
      - echo $GH_TOKEN
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make docker-hub-signin
      - make docker-pull NAME=serverless VERSION=latest
  build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - export PR_NUMBER=$(echo $CODEBUILD_WEBHOOK_TRIGGER | grep -Eo '[0-9]*')
      - echo $PR_NUMBER
      - export ENVIRONMENT=$(make -s get-environment-from-pr PR_NUMBER=$PR_NUMBER)
      - echo $ENVIRONMENT
      - export ENVIRONMENT_DEPLOYED=$(make -s is-environment-deployed ENVIRONMENT=$ENVIRONMENT)
      - echo $ENVIRONMENT_DEPLOYED
      - if [ -n "$ENVIRONMENT_DEPLOYED" ]; then
          make undeploy PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT ;
        fi
