# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - printenv
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make docker-hub-signin
  build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - export BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed -e "s|refs/heads/||")
      - export TARGET_VERSION=$(git rev-parse origin/$BRANCH_NAME)
      - make re-tag-images-for-deployment SOURCE=$CODEBUILD_RESOLVED_SOURCE_VERSION TARGET=$TARGET_VERSION
