# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - make wait-for-codebuild-to-finish PROJECT_NAME=$TESTER_BUILD_PROJECT_NAME
      - aws sts get-caller-identity
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - make docker-hub-signin
  build:
    commands:
      - aws sts get-caller-identity
      - echo "[Running Unit Tests]"
      - make docker-pull NAME=tester VERSION=latest
      - make unit-test
reports:
  unit-tests:
    files:
      - testresults.xml
    base-directory: $CODEBUILD_SRC_DIR/application
    discard-paths: yes
    file-format: JUNITXML
