# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  build:
    commands:
      - cd application
      - python -m pytest --junitxml=./testresults.xml --cov-report term-missing  --cov-report xml:coverage.xml --cov=. -vv
reports:
  unit-tests:
    files:
      - testresults.xml
    base-directory: $CODEBUILD_SRC_DIR/application
    discard-paths: yes
    file-format: JUNITXML
