name: "Check Pull Request Checklist"
on:
  pull_request:
    types: [opened, ready_for_review, edited, synchronize, reopened]
jobs:
  pull-request-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v1
        with:
          requireChecklist: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
