name: "Check code format and quality"
on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tester Build
        run: |
          make tester-build
      - name: Check text files format
        run: |
          build/automation/etc/githooks/scripts/editorconfig-pre-commit.sh
      - name: Check Python Formatting
        run: |
          make python-linting
      - name: Check Python Imports
        run: |
          make python-check-imports
      - name: Check for Python Dead Code
        run: |
          make python-check-dead-code
      - name: Check Python Unit Test Coverage
        run: |
          make coverage-report
      - uses: sonarsource/sonarcloud-github-action@master
        # SEE: https://github.com/SonarSource/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=application,deployment,infrastructure,scripts,test
            -Dsonar.organization=nhsd-exeter
            -Dsonar.projectKey=uec-dos-int
            -Dsonar.coverage.exclusions=tests/**,**/tests/**,deployment,infrastructure,application/dos_db_handler/**,test/**,scripts/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.9
            -Dsonar.exclusions=application/**/tests/**
