name: "Check code for Security Vulnerabilities"

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  check-code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if code contains any Terraform Security Vulnerabilities
        run: make terraform-security
      - name: Checkov Security and Best Practices - Serverless Framework
        run: make -s serverless-best-practices
      - name: Checkov Security and Best Practices - Docker
        run: make -s docker-best-practices
      - name: Checkov Security and Best Practices - Terraform
        run: make -s terraform-best-practices
      - name: Checkov Security and Best Practices - Github Actions
        run: make -s github-actions-best-practices
