name: "Check code for Secrets"

on: push

permissions:
  contents: read

jobs:
  check-code-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if code contains any secrets
        run: make git-config git-secrets-scan-repo-files
      - name: Checkov Secret Scanner
        run: make checkov-secret-scanning
