name: "Check code format and quality"

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

permissions:
  contents: read

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check text files format
        run: |
          build/automation/etc/githooks/scripts/editorconfig-pre-commit.sh
      - name: Tester Build
        run: |
          make tester-build
      - name: Check Python Unit Test Coverage
        run: |
          make coverage-report
      - uses: sonarsource/sonarcloud-github-action@master
        # SEE: https://github.com/SonarSource/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=application,deployment,infrastructure,scripts,test,build/docker
            -Dsonar.organization=nhsd-exeter
            -Dsonar.projectKey=uec-dos-int
            -Dsonar.coverage.exclusions=tests/**,**/tests/**,deployment,infrastructure,application/dos_db_handler/**,test/**,scripts/**,application/conftest.py
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.11
            -Dsonar.exclusions=application/**/tests/**

  check-markdown-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Markdown format
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          config: .github/workflows/configs/.markdownlint.json
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: .github/workflows/configs/markdown-check-links.json
          base-branch: develop
          file-path: "./README.md"
          check-modified-files-only: "yes"

  check-python-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tester Build
        run: |
          make tester-build
      - name: Check Python Formatting
        run: |
          make python-linting
      - name: Check for Python Dead Code
        run: |
          make python-check-dead-code
