name: "Check code for Secrets and Security Vulnerabilities"
on: push
jobs:
  check-code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if code contains any secrets
        run: make git-config git-secrets-scan-repo-files
      - name: Check if code contains any Terraform Security Vulnerabilities
        run: make terraform-security
