name: "Check code format and quality"
on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check text files format
        run: |
          build/automation/etc/githooks/scripts/editorconfig-pre-commit.sh
      - name: Check Python files format
        run: |
          make python-linting
      - name: Check Terraform files format
        run: |
          build/automation/etc/githooks/scripts/terraform-format-pre-commit.sh
      - name: Create coverage report
        run: |
          make tester-build coverage-report
      - uses: sonarsource/sonarcloud-github-action@master
        # SEE: https://github.com/SonarSource/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=application,deployment,infrastructure
            -Dsonar.organization=nhsd-exeter
            -Dsonar.projectKey=uec-dos-int
            -Dsonar.coverage.exclusions=tests/**,**/tests/**,deployment,infrastructure
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.9
            -Dsonar.exclusions=application/**/tests/**
