name: Trigger AWS CodePipeline

on:
  push:
    branches:
      - task/DS-*

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Trigger CodePipeline via Make
        run: make aws-codepipeline-trigger NAME=uec-dos-int-dev-development-pipeline AWS_REGION=eu-west-2
