name: Trigger AWS CodePipeline

on:
  push:
    branches:
      - task/DS-*

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger CodePipeline via Make
        run: make aws-codepipeline-trigger NAME=uec-dos-int-dev-development-pipeline AWS_REGION=eu-west-2
