name: "Update Pull Request with Template"
on:
  pull_request:
    types: [created]

jobs:
  update-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get branch number
        run: echo "BRANCH_NUMBER=$(echo ${{ github.ref_name }} | grep -Eo '[A-Za-z]{2,5}-[0-9]{1,5}')" >> $GITHUB_ENV
      - name: Get branch designator
        run: echo "BRANCH_DESIGNATOR=$(echo ${{ github.ref_name }} | sed 's|/.*||')" >> $GITHUB_ENV
      - name: Render Pull Request template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/pull-request-templates/${{ env.BRANCH_DESIGNATOR }}_pull_request_template.md
          vars: |
            BRANCH_NUMBER: ${{ env.BRANCH_NUMBER }}
            BRANCH_DESIGNATOR: ${{ env.BRANCH_DESIGNATOR }}
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: 'develop'
          head-branch-regex: ' ${{ github.ref_name }}'
          body-template: ${{ steps.template.outputs.result }}
          body-update-action: 'suffix'
          body-uppercase-base-match: false
